<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Storage;

/**
 * A shareable upload: an image, a PDF, or a (large) downloadable file.
 *
 * Images/PDF live on the public disk for hotlinking; archives & installers live
 * on the local/R2 disk and are served through a signed download route. Each
 * asset exposes a public landing page at /d/{slug} with a ready-made share kit.
 */
class Asset extends Model
{
    use HasFactory;
    use HasUuids;

    protected $fillable = [
        'uuid', 'slug', 'user_id', 'upload_session_id', 'kind', 'disk', 'path',
        'original_name', 'mime_type', 'size_bytes', 'checksum_sha256',
        'width', 'height', 'variants', 'pages', 'password', 'expires_at',
        'is_active', 'downloads_count', 'views_count', 'meta',
    ];

    protected $hidden = ['password'];

    protected function casts(): array
    {
        return [
            'variants' => 'array',
            'meta' => 'array',
            'is_active' => 'boolean',
            'expires_at' => 'datetime',
        ];
    }

    /** Remove the stored file (+ image variants) whenever an asset is deleted. */
    protected static function booted(): void
    {
        static::deleting(function (Asset $asset) {
            foreach ((array) $asset->variants as $variant) {
                if (! empty($variant['path'])) {
                    Storage::disk('public')->delete($variant['path']);
                }
            }
            try {
                Storage::disk($asset->disk)->delete($asset->path);
            } catch (\Throwable $e) {
                // disk may be unavailable (e.g. R2 offline) — don't block the delete
            }
        });
    }

    /** uuid is generated by HasUuids; keep slug as the route key. */
    public function uniqueIds(): array
    {
        return ['uuid'];
    }

    public function scopeForUser($query, int $userId)
    {
        return $query->where('user_id', $userId);
    }

    /** active | disabled | expired — for the management UI. */
    public function statusKey(): string
    {
        if (! $this->is_active) {
            return 'disabled';
        }

        return $this->isExpired() ? 'expired' : 'active';
    }

    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function uploadSession(): BelongsTo
    {
        return $this->belongsTo(UploadSession::class);
    }

    // --- Type helpers ----------------------------------------------------

    public function isImage(): bool
    {
        return $this->kind === 'image';
    }

    public function isPdf(): bool
    {
        return $this->kind === 'pdf';
    }

    public function isFile(): bool
    {
        return $this->kind === 'file';
    }

    public function hasPassword(): bool
    {
        return filled($this->password);
    }

    public function isExpired(): bool
    {
        return $this->expires_at !== null && $this->expires_at->isPast();
    }

    public function isAvailable(): bool
    {
        return $this->is_active && ! $this->isExpired();
    }

    // --- URLs ------------------------------------------------------------

    /** Public landing page with the share kit. */
    public function pageUrl(): string
    {
        return route('assets.show', $this);
    }

    /** The download route (counts hits, honours password/expiry). */
    public function downloadUrl(): string
    {
        return route('assets.download', $this);
    }

    /** A directly embeddable/hotlinkable URL (images & PDF on the public disk). */
    public function directUrl(): ?string
    {
        if ($this->disk === 'public') {
            return Storage::disk('public')->url($this->path);
        }

        // Non-public files are only reachable through the download route.
        return $this->downloadUrl();
    }

    public function variantUrl(string $size): ?string
    {
        $path = data_get($this->variants, "{$size}.path");

        if (! $path) {
            return $this->directUrl();
        }

        return Storage::disk('public')->url($path);
    }

    public function thumbUrl(): ?string
    {
        return $this->isImage() ? $this->variantUrl('thumb') : null;
    }
}
