<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Storage;

/**
 * A shareable upload: an image, a PDF, or a (large) downloadable file.
 *
 * Images/PDF live on the public disk for hotlinking; archives & installers live
 * on the local/R2 disk and are served through a signed download route. Each
 * asset exposes a public landing page at /d/{slug} with a ready-made share kit.
 */
class Asset extends Model
{
    use HasFactory;
    use HasUuids;

    protected $fillable = [
        'uuid', 'slug', 'user_id', 'upload_session_id', 'kind', 'disk', 'path',
        'original_name', 'mime_type', 'size_bytes', 'checksum_sha256',
        'width', 'height', 'variants', 'pages', 'password', 'expires_at',
        'is_active', 'downloads_count', 'views_count', 'meta',
    ];

    protected $hidden = ['password'];

    protected function casts(): array
    {
        return [
            'variants' => 'array',
            'meta' => 'array',
            'is_active' => 'boolean',
            'expires_at' => 'datetime',
            'reviewed_at' => 'datetime', // moderation: formatted on the review page
        ];
    }

    /** Remove the stored file (+ image variants) whenever an asset is deleted. */
    protected static function booted(): void
    {
        // Moderation: members' uploads enter the review queue (staff/trusted → approved).
        static::creating(function (Asset $asset) {
            if (blank($asset->moderation_status) || $asset->moderation_status === \App\Support\FileModeration::PENDING) {
                $asset->moderation_status = \App\Support\FileModeration::initialStatus($asset);
            }
        });
        static::created(fn (Asset $asset) => \App\Support\FileModeration::afterCreated($asset));

        // A rejected file stays off, whatever a later edit (e.g. by its owner) tries.
        static::saving(function (Asset $asset) {
            if ($asset->moderation_status === \App\Support\FileModeration::REJECTED) {
                $asset->is_active = false;
            }
        });

        // Keep protected images/PDF off the public web root (see syncVisibility).
        static::saved(fn (Asset $asset) => $asset->syncVisibility());

        static::deleting(function (Asset $asset) {
            foreach ((array) $asset->variants as $variant) {
                if (! empty($variant['path'])) {
                    Storage::disk($asset->mediaDisk())->delete($variant['path']);
                }
            }
            try {
                Storage::disk($asset->disk)->delete($asset->path);
            } catch (\Throwable $e) {
                // disk may be unavailable (e.g. R2 offline) — don't block the delete
            }
        });
    }

    /** uuid is generated by HasUuids; keep slug as the route key. */
    public function uniqueIds(): array
    {
        return ['uuid'];
    }

    public function scopeForUser($query, int $userId)
    {
        return $query->where('user_id', $userId);
    }

    /** active | disabled | expired — for the management UI. */
    public function statusKey(): string
    {
        if (! $this->is_active) {
            return 'disabled';
        }

        return $this->isExpired() ? 'expired' : 'active';
    }

    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function uploadSession(): BelongsTo
    {
        return $this->belongsTo(UploadSession::class);
    }

    public function reviewer(): BelongsTo
    {
        return $this->belongsTo(User::class, 'reviewed_by');
    }

    public function reviews(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(AssetReview::class)->latest('created_at')->latest('id');
    }

    public function reports(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(AssetReport::class)->latest();
    }

    public function isRejected(): bool
    {
        return $this->moderation_status === \App\Support\FileModeration::REJECTED;
    }

    // --- Type helpers ----------------------------------------------------

    public function isImage(): bool
    {
        return $this->kind === 'image';
    }

    public function isPdf(): bool
    {
        return $this->kind === 'pdf';
    }

    public function isFile(): bool
    {
        return $this->kind === 'file';
    }

    public function hasPassword(): bool
    {
        return filled($this->password);
    }

    public function isExpired(): bool
    {
        return $this->expires_at !== null && $this->expires_at->isPast();
    }

    public function isAvailable(): bool
    {
        return $this->is_active && ! $this->isExpired();
    }

    // --- Protection / visibility ----------------------------------------

    /** Password, an expiry date, or disabled → must not be reachable by a raw /storage URL. */
    public function isProtected(): bool
    {
        return $this->hasPassword() || $this->expires_at !== null || ! $this->is_active;
    }

    /** Images & PDF: the disk their original + variants currently live on. */
    public function mediaDisk(): string
    {
        return $this->disk === 'local' ? 'local' : 'public';
    }

    /**
     * Images/PDF are born on the public disk (hotlinkable). While protected they
     * move to the private disk and are served only via /d/{slug}/view, which
     * enforces password/expiry/active — previously the direct /storage/... URL
     * (already handed out in the share kit) kept working and bypassed all three.
     */
    public function syncVisibility(): void
    {
        if (! ($this->isImage() || $this->isPdf())) {
            return;
        }

        $from = $this->mediaDisk();
        $to = $this->isProtected() ? 'local' : 'public';
        if ($from === $to) {
            return;
        }

        $paths = array_filter([$this->path, ...array_map(fn ($v) => $v['path'] ?? null, (array) $this->variants)]);
        foreach ($paths as $p) {
            $src = Storage::disk($from)->path($p);
            if (! is_file($src)) {
                continue;
            }
            $dst = Storage::disk($to)->path($p);
            if (! is_dir(dirname($dst))) {
                mkdir(dirname($dst), 0775, true);
            }
            rename($src, $dst);
        }

        $this->forceFill(['disk' => $to])->saveQuietly();
    }

    // --- URLs ------------------------------------------------------------

    /** Public landing page with the share kit. */
    public function pageUrl(): string
    {
        return route('assets.show', $this);
    }

    /** The download route (counts hits, honours password/expiry). */
    public function downloadUrl(): string
    {
        return route('assets.download', $this);
    }

    /** Filename served on download — optionally branded with the site domain. */
    public function downloadName(): string
    {
        $name = (string) $this->original_name;

        if (! Setting::get('brand_downloads', true)) {
            return $name;
        }

        $host = parse_url((string) config('app.url'), PHP_URL_HOST) ?: '';

        if ($host === '' || str_starts_with($name, $host.'-')) {
            return $name; // no host, or already branded
        }

        return $host.'-'.$name;
    }

    /** A directly embeddable/hotlinkable URL (images & PDF on the public disk). */
    public function directUrl(): ?string
    {
        if ($this->disk === 'public') {
            return Storage::disk('public')->url($this->path);
        }

        // Protected image/PDF: inline view through the guarded route.
        if ($this->isImage() || $this->isPdf()) {
            return route('assets.view', $this);
        }

        // Non-public files are only reachable through the download route.
        return $this->downloadUrl();
    }

    public function variantUrl(string $size): ?string
    {
        $path = data_get($this->variants, "{$size}.path");

        if (! $path) {
            return $this->directUrl();
        }

        if ($this->disk !== 'public') {
            return route('assets.view', ['asset' => $this, 'size' => $size]);
        }

        return Storage::disk('public')->url($path);
    }

    public function thumbUrl(): ?string
    {
        return $this->isImage() ? $this->variantUrl('thumb') : null;
    }
}
